app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include("backend.urls")),
    path('users/', include("users.urls")),
    path('admin/', admin.site.urls),
]

backend/urls.py
from django.urls import path, re_path, include
from rest_framework import routers
from .api import *
from . import views

app_name = "backend"
router = routers.DefaultRouter()
router.register(r'records', RecordViewSet, 'records')
router.register(r'users', UserViewSet, 'users')

urlpatterns = [
     path('',views.index, name="index"),
     path('settings/',views.settings, name="settings"),
     re_path('data/', include((router.urls)))
]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
	#Include default auth urls.
	path('', include('django.contrib.auth.urls')),
    path('register/',views.register,name='register')
]

backend/models.py
from django.db import models
from django.contrib.auth.models import User

EMAIL_FREQUENCY = [
        ('daily',"Daily"),
        ('daily',"Weekly"),
        ('daily',"Monthly"),
    ]

class Record(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=200, blank=True)
    created_by = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=200, blank=True)
    details = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name_plural = 'records'


class UserSettings(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=200, blank=True)
    email = models.CharField(max_length=200, blank=True)
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    mobile = models.CharField(max_length=200, blank=True)
    password = models.CharField(max_length=200, blank=True)
    receive_emails = models.BooleanField(default=True)
    email_frequency = models.CharField(choices = EMAIL_FREQUENCY, max_length=200, default=EMAIL_FREQUENCY[0])
    
    class Meta:
        verbose_name_plural = 'settings'

users/models.py
from django.db import models

# Create your models here.

backend/forms.py
from django import forms 
from .models import Record, UserSettings

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = '__all__'


class SettingsForm(forms.ModelForm):
    class Meta:
        model = UserSettings
        fields = '__all__'

backend/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from .forms import RecordForm, SettingsForm
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, "backend/index.html")

@login_required
def settings(request):
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = SettingsForm()
    else:
        #POST data submitted; process data.
        form = SettingsForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('backend:index.html')
    
    #Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'backend/index.html', context)


@login_required
def new_record(request):
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = RecordForm()
    else:
        #POST data submitted; process data.
        form = RecordForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('backend:index.html')
    
    #Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'backend/index.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm 

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        #Display blank registration form
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Log the user in then redirect to home page.
            login(request, new_user)
            return redirect('backend:index')

    # Display a blank or valid form.
    context = {'form': form}
    return render(request, 'registration/register.html',context)

backend/templates/backend/base.html
{# Load CSS and JavaScript for bootstrap #}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>Django App Template</title>
</head>
<body>
    <div class="container" style="margin: auto; width: 100%;">
        <div id="header" class="row border-bot-1-light" style="margin: auto; width: 100%; height: 75px; padding-top: 5px;">

            <div class="col-10">
                <img src="{% static 'images/nleyetn_logo.jpg' %}#logo" height="60">
            </div>
            
            <div class="col-2 text-right">
                <a href="{% url 'backend:index' %}">
                    <img src="{% static 'images/home_icon.svg' %}#home" alt="Home" height="50">
                </a>
                
                <a href="{% url 'backend:settings' %}">
                    <img src="{% static 'images/settings_icon.svg' %}#settings" alt="Settings" height="50">
                </a>
            </div>
        </div>

        <div id="body" class="row mt-5" style="margin: auto; width: 100%;">
            {% block content %}{% endblock %}
        </div>

    </div>
</body>
</html>

backend/templates/backend/form.html
{% extends 'backend/base.html' %}

{% block content %}
  <form action="/" method="post" class="form">
    {% csrf_token %}
    <label for="name">Name:</label>
    <input name="name" id="name">
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        Submit
      </button>
    {% endbuttons %}
  </form>
{% endblock content %}

backend/templates/backend/index.html
{% extends 'backend/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-10">
                <div class="row p-3">
                    <div class="input-group">
                        <input type="text" class="form-control" aria-label="Text input with segmented dropdown button">
                        <div class="input-group-append">
                          <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only">Filter</span>
                          </button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">All</a>
                            <div role="separator" class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Suppliers</a>
                                <a class="dropdown-item" href="#">Catalogs</a>
                                <a class="dropdown-item" href="#">Contracts</a>
                                <div role="separator" class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Orders</a>
                                <a class="dropdown-item" href="#">Invoices</a>
                                <a class="dropdown-item" href="#">Payments</a>
                                <div role="separator" class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Reports</a>
                                <a class="dropdown-item" href="#">Documents</a>
                          </div>
                        </div>
                      </div>
                </div>
                
                <div class="row p-3">
                    <div class="col-2 d-flex"></div>
                    <div class="col-10 d-flex justify-content-between"">
                        <a class="btn btn-light m">Catalogs</a>
                        <a class="btn btn-light m">Suppliers</a>
                        <a class="btn btn-light m">Contracts</a>
                        <a class="btn btn-light m">Orders</a>
                        <a class="btn btn-light m">Invoices</a>
                        <a class="btn btn-light m">Payments</a>
                        <a class="btn btn-light m">Reports</a>
                    </div>
                    <div class="col-2 d-flex"></div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <iframe style="width: 100%; height: 800px; overflow-y: scroll; border: 1px solid lightgray;"></iframe>
                    </div>
                </div>
            </div> 
            <div class="col-2"></div>
        </div>
    </div>
    </div>
    
      
   
{% endblock content %}

backend/templates/backend/settings.html
{% extends 'backend/base.html' %}

{# Load CSS and JavaScript for bootstrap #}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
  <form action="/" method="post" class="form">
    {% csrf_token %}
    {% form.as_p %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
  </form>

  
{% endblock content %}